[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]

[phases.install]
cmds = [
  "cd vrp_rl_project",
  "python -m pip install --user -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "cd vrp_rl_project && python -m uvicorn backend_api:app --host 0.0.0.0 --port $PORT" 