# API Configuration
api:
  google_maps:
    base_url: "https://maps.googleapis.com/maps/api"
    traffic_endpoint: "/traffic/v1"
  openweather:
    base_url: "https://api.openweathermap.org/data/2.5"
    weather_endpoint: "/weather"

# Environment Configuration
environment:
  max_capacity: 6000  # Sesuai dengan data PT. Sanghiang
  time_window: 24
  depot_location: [-6.2088, 106.8456]  # Jakarta Timur

# RL Model Configuration (OPTIMIZED)
model:
  learning_rate: 0.0005  # Lebih stabil untuk DQN
  gamma: 0.99
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay: 0.995
  memory_size: 50000  # Lebih banyak experience
  batch_size: 32  # Lebih kecil untuk stabilitas
  target_update: 10
  hidden_layers: [256, 256, 128]  # Arsitektur lebih dalam

# Training Configuration
training:
  episodes: 2000  # Lebih banyak episode
  max_steps: 100
  save_interval: 100
  evaluation_interval: 50

# Weather Impact Factors
weather_impact:
  rain: 1.2  # 20% slower
  snow: 1.5  # 50% slower
  fog: 1.3   # 30% slower
  clear: 1.0 # normal speed

# Traffic Impact Factors
traffic_impact:
  low: 1.0    # normal speed
  medium: 1.3 # 30% slower
  high: 1.6   # 60% slower 